name: Vocabularies  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /vocabularies get lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-g.zip vocabularies/get/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-g
            zip_file: m-s-vocabularies-g.zip
      - name: /vocabularies post lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-po.zip vocabularies/post/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-po
            zip_file: m-s-vocabularies-po.zip
      - name: /vocabularies/{vocabulary_id} get lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-vocabulary-g.zip vocabularies/vocabulary_id/get/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-vocabulary-g
            zip_file: m-s-vocabularies-vocabulary-g.zip
      - name: /vocabularies/{vocabulary_id} put lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-vocabulary-pu.zip vocabularies/vocabulary_id/put/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-vocabulary-pu
            zip_file: m-s-vocabularies-vocabulary-pu.zip
      - name: /vocabularies/{vocabulary_id} delete lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-vocabulary-d.zip vocabularies/vocabulary_id/delete/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-vocabulary-d
            zip_file: m-s-vocabularies-vocabulary-d.zip          