name: Vocabularies  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - name: /vocabularies get lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-g.zip vocabularies/get/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-g
            zip_file: m-s-vocabularies-g.zip
      - name: /vocabularies post lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-po.zip vocabularies/post/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-po
            zip_file: m-s-vocabularies-po.zip
      - name: /vocabularies/content post lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabulariescontent-po.zip vocabularies/content/post/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabulariescontent-po
            zip_file: m-s-vocabulariescontent-po.zip
      - name: /vocabularies/content/links post lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabulariescontentlinks-po.zip vocabularies/content/links/post/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabulariescontentlinks-po
            zip_file: m-s-vocabulariescontentlinks-po.zip
      - name: /vocabularies/search get lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabulariessearch-g.zip vocabularies/search/get/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabulariessearch-g
            zip_file: m-s-vocabulariessearch-g.zip
      - name: /vocabularies/search post lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabulariessearch-po.zip vocabularies/search/post/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabulariessearch-po
            zip_file: m-s-vocabulariessearch-po.zip
      - name: /vocabularies/{vocabulary_id} get lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-vocabulary-g.zip vocabularies/vocabulary_id/get/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-vocabulary-g
            zip_file: m-s-vocabularies-vocabulary-g.zip
      - name: /vocabularies/{vocabulary_id} put lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-vocabulary-pu.zip vocabularies/vocabulary_id/put/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-vocabulary-pu
            zip_file: m-s-vocabularies-vocabulary-pu.zip
      - name: /vocabularies/{vocabulary_id} delete lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-vocabulary-d.zip vocabularies/vocabulary_id/delete/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-vocabulary-d
            zip_file: m-s-vocabularies-vocabulary-d.zip
      - name: /vocabularies/{vocabulary_id}/tags get lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-vocabulary-tags-g.zip vocabularies/vocabulary_id/tags/get/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-vocabulary-tags-g
            zip_file: m-s-vocabularies-vocabulary-tags-g.zip
      - name: /vocabularies/{vocabulary_id}/tags post lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-vocabulary-tags-po.zip vocabularies/vocabulary_id/tags/post/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-vocabulary-tags-po
            zip_file: m-s-vocabularies-vocabulary-tags-po.zip
      - name: /vocabularies/{vocabulary_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/vocabularies@main
        with:
            args: zip -qq -r m-s-vocabularies-vocabulary-tags-tag-d.zip vocabularies/vocabulary_id/tags/tag_id/delete/index.js node_modules
      - name: vocabularies get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-vocabularies-vocabulary-tags-tag-d
            zip_file: m-s-vocabularies-vocabulary-tags-tag-d.zip